# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "tag-daily-orders"
client_id = "f1aa7b585d05c1febaa2ea3ff7d2eb1f"
application_url = "https://75c9-79-174-251-211.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://75c9-79-174-251-211.ngrok-free.app/auth/callback",
  "https://75c9-79-174-251-211.ngrok-free.app/auth/shopify/callback",
  "https://75c9-79-174-251-211.ngrok-free.app/api/auth/callback",
  "https://75c9-79-174-251-211.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "benitos-santos.myshopify.com"
